
CREATE OR ALTER PROCEDURE FI_SP_IncBeneficiarioV2
    @IDCLIENTE     BIGINT       ,     
    @NOME          VARCHAR (50) ,
    @CPF           VARCHAR (11) 
    
AS
BEGIN
	INSERT INTO BENEFICIARIO (IDCLIENTE ,NOME, CPF) 
	VALUES (@IDCLIENTE,@NOME, @CPF)

	SELECT SCOPE_IDENTITY()
END